openapi: 3.0.0
info:
  description: API to generate paths based on field and working lanes data.
  title: Path Generation API
  version: 1.0.0
servers:
- url: /
paths:
  /generatePath:
    post:
      operationId: generate_path_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_generatePath_post_request'
        required: true
        x-body-name: generate_path_post_request
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Path'
          description: Path generated successfully
        "400":
          description: Invalid input
        "500":
          description: Internal server error
      summary: Generate a path based on field data
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    Path:
      example:
        len: 0.0
        angle: 0.0
        point:
          x: 0
          "y": 0
          z: 0
      properties:
        point:
          $ref: '#/components/schemas/Point'
        angle:
          description: Angle of the path
          example: 0.0
          title: angle
          type: number
        len:
          description: Length of the path (must be >= 0)
          example: 0.0
          minimum: 0
          title: len
          type: number
      title: Path
      type: object
    Point:
      example:
        x: 0
        "y": 0
        z: 0
      properties:
        x:
          description: X coordinate
          example: 0
          title: x
          type: number
        "y":
          description: Y coordinate
          example: 0
          title: "y"
          type: number
        z:
          description: Z coordinate
          example: 0
          title: z
          type: number
      title: Point
      type: object
    _generatePath_post_request_settings:
      properties:
        robotSettings:
          $ref: '#/components/schemas/Robot_Settings'
        sorterSettings:
          $ref: '#/components/schemas/_generatePath_post_request_settings_sorterSettings'
        curvesAlgorithm:
          description: Algorithm to generate curves
          enum:
          - dubins
          - dubins_cc
          - reeds_shepp
          example: dubins
          title: curvesAlgorithm
          type: string
      title: _generatePath_post_request_settings
      type: object
    _generatePath_post_request:
      properties:
        workingLanes:
          description: Optional GeoJSON data for working lanes
          format: geojson
          title: workingLanes
          type: string
        transportLanes:
          description: Optional GeoJSON data for transport lanes
          format: geojson
          title: transportLanes
          type: string
        startEndPoint:
          $ref: '#/components/schemas/Point'
        robotSettings:
          $ref: '#/components/schemas/_generatePath_post_request_settings/properties/robotSettings'
        sorterSettings:
          $ref: '#/components/schemas/_generatePath_post_request_settings/properties/sorterSettings'
        curvesAlgorithm:
          $ref: '#/components/schemas/_generatePath_post_request_settings/properties/curvesAlgorithm'
      required:
      - curvesAlgorithm
      - robotSettings
      - sorterSettings
      - startEndPoint
      - transportLanes
      - workingLanes
      title: _generatePath_post_request
      type: object
    Robot_Settings:
      properties:
        width:
          description: Width of the robot
          example: 2.0
          title: width
          type: number
        cov_width:
          description: Width of the headland
          example: 3.0
          title: cov_width
          type: number
        max_curv:
          description: Maximum curvature
          example: 0.5
          title: max_curv
          type: number
        max_diff_curv:
          description: Maximum difference in curvature
          example: 0.2
          title: max_diff_curv
          type: number
        min_turning_radius:
          description: Minimum turning radius
          example: 2.0
          title: min_turning_radius
          type: number
      title: Robot Settings
      type: object
    _generatePath_post_request_settings_sorterSettings:
      properties:
        algorithm:
          description: Algorithm to sort the swaths
          enum:
          - snake
          - boustrophedon
          - spiral
          - optimal
          example: snake
          title: sorterAlgorithm
          type: string
        variant:
          description: Variant of the sorter algorithm (1..4)
          example: 1
          title: sorterVariant
          type: integer
          default: 1
        spiralSize:
          description: Size of the spiral
          example: 10
          title: spiralSize
          type: integer
      required:
      - algorithm      
      title: _generatePath_post_request_settings_sorterSettings
